services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: myKino
      POSTGRES_USER: silvan
      POSTGRES_PASSWORD: julianHagel
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U silvan -d myKino || exit 1" ]
      start_period: 10s
      interval: 30s
      timeout: 40s
      retries: 2



      #depends_on
        #condition: service-healthy

