name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
