name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ch.bbw.M347.repository
        uses: actions/checkout@v4
