name: Continuous Integration
on:
  push:
    branches: [ "master" ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Repo
        uses: actions/checkout@v4
        
      - name: Create test .env file
        run:|
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

       - name: Start Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
          up-flags: "--build -d"
  

    
